server:
  port: 3000

spring:
  cloud:
    gateway:
      routes:
        - id: userService
          uri: http://localhost:3001/
          predicates:
            - Path=/person/**
        - id: covidStateService
          uri: http://localhost:3002/
          predicates:
            - Path=/covidState/**
            - Path=/personState/**
        - id: positionService
          uri: http://localhost:3003/
          predicates:
            - Path=/positions/**
        - id: notificationService
          uri: http://localhost:3004/
          predicates:
            - Path=/notifications/**
        - id: suspiciousLocationService
          uri: http://localhost:3005/
          predicates:
            - Path=/suslocation/**